Add a check for memory unit
kruize/benchmarks pull request #11
Opened 2021-02-01 08:20 UTC by shruacha1234

Signed-off-by: Shruthi <Shruthi.Acharya@ibm.com>

2021-02-01 10:47 UTC, dinogun requested changes
We cannot assume that it is always in `MiB` units. We need to add a comment in the "command help" section that this unit needs to be always specified in `MiB`

2021-02-01 12:28 UTC, shruacha1234 commented
> We cannot assume that it is always in `MiB` units. We need to add a comment in the "command help" section that this unit needs to be always specified in `MiB`

Need not add a check for memory unit?

2021-02-07 14:21 UTC, dinogun commented on spring-petclinic/scripts/petclinic-deploy-openshift.sh
> +case "${MEM_REQ}" in
Suggest you create a function for checking the memory unit and call it for both `MEM_REQ` and `CPU_REQ`.

2021-02-13 13:56 UTC, dinogun approved these changes
lgtm !

2021-02-13 13:56 UTC, merged