Add scripts fpr TFB-quarkus benchmarks.
kruize/benchmarks pull request #29
Opened 2021-05-04 10:14 UTC by kusumachalasani

2021-05-10 06:14 UTC, dinogun requested changes
In addition to the individual comments, I see this PR uses both camel casing and underscores for function names. Please use only underscores for all function names.

2021-05-21 14:03 UTC, chandrams commented on techempower/scripts/tfb-qrh-deploy-openshift.sh
> +#!/bin/bash
@kusumachalasani - Can you include a README with details on how to run this benchmark

2021-05-24 15:26 UTC, chandrams commented on techempower/scripts/perf/run-tfb-qrh-openshift.sh
> +while getopts s:e:w:m:i:rg:n:t:R:d:-: gopts
Include -u option here

2021-06-01 10:17 UTC, chandrams commented on techempower/manifests/quarkus-resteasy-hibernate.yaml
> +        image: kusumach/tfb-qrh-mm:1.13.2.F
Shouldn't we keep the images under kruize in docker hub?

2021-06-01 10:17 UTC, chandrams commented on techempower/manifests/service-monitor.yaml
> +    - port: tfb-qrh-port
Should we change the path to /q/metrics ?

2021-06-01 10:22 UTC, chandrams commented on techempower/scripts/perf/run-tfb-qrh-openshift.sh
> +			${SCRIPT_REPO}/tfb-qrh-deploy-openshift.sh -s ${BENCHMARK_SERVER} -i ${SCALING} -g ${TFB_IMAGE} --cpureq=${CPU_REQ} --memreq=${MEM_REQ} --cpulim=${CPU_LIM} --memlim=${MEM_LIM} --maxinlinelevel=${m
setup.log should be created in results dir

2021-06-01 10:26 UTC, chandrams commented on techempower/scripts/perf/run-tfb-qrh-openshift.sh
> +			${SCRIPT_REPO}/tfb-qrh-deploy-openshift.sh -s ${BENCHMARK_SERVER} -i ${SCALING} -g ${TFB_IMAGE} --cpureq=${CPU_REQ} --memreq=${MEM_REQ} --cpulim=${CPU_LIM} --memlim=${MEM_LIM} --maxinlinelevel=${m
Also had few echo statements to display progress. Below is a run, where nothing was displayed when I ran the script, and it just logs some metrics on failure.

```
./run-tfb-qrh-openshift.sh -s <Benchmark server> -e /home/quicklab/TFB-results -u 500 -d 600 -w 0 -m 1 -r

SCALE ,  THROUGHPUT_RATE_3m , RESPONSE_TIME_RATE_3m , THROUGHPUT , RESPONSE_TIME , MAX_RESPONSE_TIME , RESPONSE_TIME_50p , RESPONSE_TIME_95p , RESPONSE_TIME_98p , RESPONSE_TIME_99p , RESPONSE_TIME_999p , MEM_USAGE , CPU_USAGE , CPU_MIN , CPU_MAX , MEM_MIN , MEM_MAX , thrpt_prom_ci , rsp_prom_ci	, Throughput , Responsetime , RESPONSETIME_MAX , STDEV_RESPTIME_MAX , WEB_ERRORS , thrp_wrk_ci , rsp_wrk_ci	, CPU_REQ , MEM_REQ , CPU_LIM , MEM_LIM , maxinlinelevel , quarkustpcorethreads , quarkustpqueuesize , quarkusdatasourcejdbcminsize , quarkusdatasourcejdbcmaxsize
1 , 99999 , 99999 , 99999 , 99999 , 99999 , 999999 , 99999 , 99999 , 99999 , 99999 , 99999 , 99999 , 99999 , 99999 , 99999 , 99999 , 0 , 0	, 99999 , 99999 , 99999 , 99999 , 9999 , 0 , 0	,  ,  ,  ,  ,  ,  ,  ,  , 
```

2021-06-15 07:24 UTC, chandrams commented on techempower/scripts/perf/run-tfb-qrh-openshift.sh
> +paste ${RESULTS_DIR_ROOT}/Metrics-prom.log ${RESULTS_DIR_ROOT}/Metrics-wrk.log ${RESULTS_DIR_ROOT}/Metrics-config.log
It would be good if the script indicates if the run had errors or not by parsing the Metrics-wrk.log for web_errors.

2021-06-18 12:04 UTC, kusumachalasani commented on techempower/scripts/getmetrics-promql.sh
> +function get_receive_bandwidth()
As of now, we are not using this data.

2021-06-18 12:05 UTC, kusumachalasani commented on techempower/scripts/getmetrics-promql.sh
> +{
As of now, we are not using this data.

2021-06-23 04:37 UTC, dinogun commented
@chandrams Do the latest changes work for you now ?

2021-07-19 13:07 UTC, dinogun commented
@chandrams Can you please confirm if the changes work for you

2021-07-21 05:28 UTC, chandrams commented
@dinogun - Changes had worked for me earlier, but I have not tested with the latest changes that were made. I tried testing it on my cluster, but it fails with Image Pull error.

2021-07-21 17:14 UTC, dinogun approved these changes
LGTM !

2021-07-21 17:14 UTC, merged